### ISSUE TITLE
[Feat] Add lint-staged

### ISSUE THREAD

**Issue by yuvalbl** [hasadna/anyway-newsflash-infographics#214]
Include: 
- [ ] prettier
- [ ] lint

**Comment by yuvalbl** [comment]
typescript lint:
https://www.robertcooper.me/using-eslint-and-prettier-in-a-typescript-project

CI action - change to:
```
name: CI

on:
  pull_request:
    branches:
      - development
      - master
```
