### ISSUE TITLE
[Feat] Add Deployment preview

### ISSUE THREAD

**Issue by yuvalbl** [hasadna/anyway-newsflash-infographics#674]
firebase allows Deployment preview for each PR, before merging to our main branch
https://firebase.google.com/docs/hosting/github-integration

**Comment by eidan66** [comment]
Hey @yuvalbl,
Here what need to do:
- run on terminal this command: `firebase init hosting:github` 
- then follow this instruction:
  - `Are you ready to proceed?` - write `y`
  - `For which GitHub repository would you like to set up a GitHub workflow? (format: user/repository)` - write `hasadna/anyway-newsflash-infographics`
  - `Set up the workflow to run a build script before every deploy?` - write `y`
  - ` What script should be run before every deploy?` - write `npm ci && npm run build`
  - Now, if you get this line, you can rewrite the file: ` GitHub workflow file for PR previews exists. Overwrite? firebase-hosting-pull-request.yml`

After this, you will initial firebase preview deployment.
open the new `yml` file, and past those lines:
```

name: Deploy to Firebase Hosting on PR
'on': pull_request
jobs:
    build_and_preview:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
​
            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: '14'
​
            - run: npm ci
            - run: npm run build
​
            - name: Deploy
              uses: FirebaseExtended/action-hosting-deploy@v0
              with:
                  repoToken: '${{ secrets.GITHUB_TOKEN }}'
                  firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_... }}'  // Change it to what you get in initial yml file
                  projectId: ....  // Change it to what you get in initial yml file
```
